name: kafka-mqtt-images
lang: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore: 
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ['confluentinc/cp-kafka-mqtt',]              
  maven_phase: 'package'    
  cve_scan : false                          
  maven_skip_deploy: true                   
  os_types: ['ubi8']                                    
  build_arm: true
  use_packages: true
  sign_images: true
  cp_images: true
  nano_version: true
  push_latest: true
  tasks:
    - name: cp-dockerfile-build
      branch: master
      pipeline_file: .semaphore/cp_dockerfile_build.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
          default_value: 'NONE'
        - name: PACKAGES_URL
          required: true
          default_value: 'NONE'
        - name: PACKAGES_MAVEN_URL
          required: true
          default_value: 'NONE'
        - name: PACKAGING_BUILD_NUMBER
          required: true
          default_value: 'NONE'
        - name: ALLOW_UNSIGNED
          required: true
          default_value: 'False'
          options:
            - 'True'
            - 'False'
        - name: CONFLUENT_DEB_VERSION
          required: true
          default_value: '1'
    - name: cp-dockerfile-promote
      branch: master
      pipeline_file: .semaphore/cp_dockerfile_promote.yml
      parameters:
        - name: CONFLUENT_VERSION
          required: true
          default_value: 'NONE'
        - name: IMAGE_REVISION
          required: true
          default_value: '1'
        - name: UPDATE_LATEST_TAG
          required: true
          default_value: 'NONE'
        - name: PACKAGING_BUILD_NUMBER
          required: true
          default_value: 'NONE'
        - name: PROMOTE_OS_TYPE
          required: true
          default_value: 'NONE'
          options:
            - 'deb'
            - 'ubi'
sonarqube:
  enable: true