name: kafka-mqtt-images
lang: unknown
git:
  enable: true
codeowners:
  enable: true
semaphore: 
  enable: true
  pipeline_type: cp-dockerfile
  docker_repos: ['unsynced-confluentinc/cp-kafka-mqtt',]              
  maven_phase: 'package'    
  cve_scan : false                          
  maven_skip_deploy: true                   
  os_types: ['ubi8']                                    
  build_arm: true
  use_packages: true
  cp_images: true
  nano_version: true